In [2]:
import numpy as np
A = np.array([[1, -2, 2], [3,1,1], [2,0,1]])
B = np.array([[-1,-2,4], [1,3,-5], [2,4,7]])

#e(i)
print(A-(2*B), '\n') 
print(B-A, '\n')
#e(ii)
print(A @ B, '\n')

#e(ii)
print(B@A, '\n')

#e(iii)
print((B@A).T, '\n')
print(A.T @ B.T, '\n')

#e(iv)
print(round(np.linalg.det(A)), '\n')
print(round(np.linalg.det(B)), '\n')

#e(v)
print((A+3*(np.identity(3)))*(B-B.T) , '\n')

#e(vi)
print(2*B-2*A, '\n')

#(vii)
print('7.1:', '|AB|=', round(np.linalg.det(A@B)), ' =|A||B|=', round(np.linalg.det(A)*round(np.linalg.det(B))),  '\n')
print('7.2:', '|5B|=', round(np.linalg.det(5*B)), ' =5^3|B|=', 5**3*(np.linalg.det(B)), '\n')
print('7.3:', '|A^T|=', round(np.linalg.det(A.T)), ' =|A|=', round(np.linalg.det(A)), '\n' )

#(viii)
x = np.array([3,0,6])
y = np.array([2, -1, 3])
print('8.1: ', 2*x+2*y)
print('8.2: ', A@x+A@y)
print('8.3: ', B@(2*x-3*A@y))
print('8.4: ', x@y)

[[  3   2  -6]
 [  1  -5  11]
 [ -2  -8 -13]] 

[[-2  0  2]
 [-2  2 -6]
 [ 0  4  6]] 

[[ 1  0 28]
 [ 0  1 14]
 [ 0  0 15]] 

[[ 1  0  0]
 [ 0  1  0]
 [28  0 15]] 

[[ 1  0 28]
 [ 0  1  0]
 [ 0  0 15]] 

[[ 1  0 28]
 [ 0  1  0]
 [ 0  0 15]] 

-1 

-15 

[[ 0.  6.  4.]
 [ 9.  0. -9.]
 [-4.  0.  0.]] 

[[ -4   0   4]
 [ -4   4 -12]
 [  0   8  12]] 

7.1: |AB|= 15  =|A||B|= 15 

7.2: |5B|= -1875  =5^3|B|= -1875.0 

7.3: |A^T|= -1  =|A|= -1 

8.1:  [10 -2 18]
8.2:  [25 23 19]
8.3:  [  36  -51 -207]
8.4:  24


In [13]:
#3.1

def det(t_by_t_matrix):
    return t_by_t_matrix[0][0] * t_by_t_matrix[1][1] - t_by_t_matrix[0][1] * t_by_t_matrix[1][0]
    

def inverse(matrix):
    if det(matrix) != 0:
        inverse_m = np.linalg.inv(matrix)
        print('3.1 inverse = \n', inverse_m, '\n')
        print('inverse product = \n', inverse_m @ matrix, '\n')
    

A = np.array([[-4,3], [7,8]])
B = np.array([[4,3], [8,6]])

inverse(A)
inverse(B)

3.1 inverse = 
 [[-0.1509434   0.05660377]
 [ 0.13207547  0.0754717 ]] 

inverse product = 
 [[1. 0.]
 [0. 1.]] 

