In [25]:
#1.2
#a
print(np.array([[0,4,2], [-3,1,7], [2,1,6]]).T)
print(np.array([[16,6,0], [np.sqrt(3), 2.45, 8], [7,2,np.sin(8)]]).T)
print(np.array([[24,-16,23], [np.], [2,1,6]]).T)

[[ 0 -3  2]
 [ 4  1  1]
 [ 2  7  6]]
[[16.          1.73205081  7.        ]
 [ 6.          2.45        2.        ]
 [ 0.          8.          0.98935825]]
[[ 0 -3  2]
 [ 4  1  1]
 [ 2  7  6]]


In [23]:
#2.c
print(np.array([[2,3], [1,4]]) - np.array([[3.5, 4], [3, 11.5]]))

[[-1.5 -1. ]
 [-2.  -7.5]]


In [21]:
#2.b
try:
    print(np.array([[6.5, 3.4, 9], [1,7,11], [83, 72, 34], [42, 32.5, 19]]) - np.array([[8.4, 4.7], [3.5, 11.5], [21,14]]))
except:
    print('invalid dimentions')

invalid dimentions


In [18]:
#2.c
import numpy as np
print(5*np.array([[4,-5], [3,12], [8,11]]) - 3*np.array([[3,-4], [6, -18], [7, 37]]))

[[ 11 -13]
 [ -3 114]
 [ 19 -56]]


In [16]:
#2.d

import numpy as np
A= np.array([[4,3,-6], [7, -4, -5], [-10, 3, 4], [9,1,0]])
B = np.array([[-2,4], [5,6], [4,1]])
print(A@B, '\n')
print((A@B).shape)

[[-17  28]
 [-54  -1]
 [ 51 -18]
 [-13  42]] 

(4, 2)


In [2]:
#2e
import numpy as np
A = np.array([[1, -2, 2], [3,1,1], [2,0,1]])
B = np.array([[-1,-2,4], [1,3,-5], [2,4,7]])

#e(i)
print(A-(2*B), '\n') 
print(B-A, '\n')
#e(ii)
print(A @ B, '\n')

#e(ii)
print(B@A, '\n')

#e(iii)
print((B@A).T, '\n')
print(A.T @ B.T, '\n')

#e(iv)
print(round(np.linalg.det(A)), '\n')
print(round(np.linalg.det(B)), '\n')

#e(v)
print((A+3*(np.identity(3)))*(B-B.T) , '\n')

#e(vi)
print(2*B-2*A, '\n')

#(vii)
print('7.1:', '|AB|=', round(np.linalg.det(A@B)), ' =|A||B|=', round(np.linalg.det(A)*round(np.linalg.det(B))),  '\n')
print('7.2:', '|5B|=', round(np.linalg.det(5*B)), ' =5^3|B|=', 5**3*(np.linalg.det(B)), '\n')
print('7.3:', '|A^T|=', round(np.linalg.det(A.T)), ' =|A|=', round(np.linalg.det(A)), '\n' )

#(viii)
x = np.array([3,0,6])
y = np.array([2, -1, 3])
print('8.1: ', 2*x+2*y)
print('8.2: ', A@x+A@y)
print('8.3: ', B@(2*x-3*A@y))
print('8.4: ', x@y)

[[  3   2  -6]
 [  1  -5  11]
 [ -2  -8 -13]] 

[[-2  0  2]
 [-2  2 -6]
 [ 0  4  6]] 

[[ 1  0 28]
 [ 0  1 14]
 [ 0  0 15]] 

[[ 1  0  0]
 [ 0  1  0]
 [28  0 15]] 

[[ 1  0 28]
 [ 0  1  0]
 [ 0  0 15]] 

[[ 1  0 28]
 [ 0  1  0]
 [ 0  0 15]] 

-1 

-15 

[[ 0.  6.  4.]
 [ 9.  0. -9.]
 [-4.  0.  0.]] 

[[ -4   0   4]
 [ -4   4 -12]
 [  0   8  12]] 

7.1: |AB|= 15  =|A||B|= 15 

7.2: |5B|= -1875  =5^3|B|= -1875.0 

7.3: |A^T|= -1  =|A|= -1 

8.1:  [10 -2 18]
8.2:  [25 23 19]
8.3:  [  36  -51 -207]
8.4:  24


In [13]:
#3.1

def det(t_by_t_matrix):
    return t_by_t_matrix[0][0] * t_by_t_matrix[1][1] - t_by_t_matrix[0][1] * t_by_t_matrix[1][0]
    

def inverse(matrix):
    if det(matrix) != 0:
        inverse_m = np.linalg.inv(matrix)
        print('3.1 inverse = \n', inverse_m, '\n')
        print('inverse product = \n', inverse_m @ matrix, '\n')
    

A = np.array([[-4,3], [7,8]])
B = np.array([[4,3], [8,6]])

inverse(A)
inverse(B)

3.1 inverse = 
 [[-0.1509434   0.05660377]
 [ 0.13207547  0.0754717 ]] 

inverse product = 
 [[1. 0.]
 [0. 1.]] 



In [11]:
#3.2
import numpy as np
x= np.array([11 ,-13, 7, 4])
def norms(vec):
    print(np.linalg.norm(vec,1))
    print(np.linalg.norm(vec,2))
    print(np.linalg.norm(vec,np.inf))

norms(x)

35.0
18.841443681416774
13.0


In [12]:
#3.3
import numpy as np
A = np.array([[4, -11, 12 , 5], [3, -4, -5, -6], [8, 2, 11, -7], [4,3, 9, 22]])
def norms(vec):
    print(np.linalg.norm(vec,1))
    print(np.linalg.norm(vec,np.inf))

norms(A)

40.0
38.0
